name: Request Assignment Repository
description: Instantly provision your private assignment repository using the shared monthly claim code and fullsail.edu.
title: "Private Repository Request"
labels: ["provision-repo"]
body:
  - type: markdown
    attributes:
      value: |
        ### Welcome to the OPS Course!
        Clicking submit below will generate your personal, private workspace under our organization.
  - type: input
    id: email
    attributes:
      label: Full Sail Email
      description: Must be a valid Full Sail email address ending in student.fullsail.edu (e.g. yourname@student.fullsail.edu).
      placeholder: yourname@student.fullsail.edu
    validations:
      required: true
  - type: input
    id: passcode
    attributes:
      label: Claim Code
      placeholder: Enter the passcode provided by your instructor.
    validations:
      required: true
